### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by Dope25** [Danixu/project-zomboid-server-docker#1]
Hi,

if you leave the IP and STEAMPORT at default (IP="", STEAMPORT1="", STEAMPORT2=""), it fails to fall back to default and instead in order succeed in docker-compose you need to remove the quotation marks and leave blanks for it to fall back to default.

Some troubleshooting I had go through to get it to work.

Successful parameters:
IP=
STEAMPORT1=
STEAMPORT2=

Unsuccessful parameters:
IP=""
STEAMPORT1=""
STEAMPORT2=""

**Comment by Danixu** [comment]
Hello,

Thanks for the report. I was not able to reproduce the error on my computer but maybe I am using a different SO or different versions of the programs. I have removed the quotes from the template and I have done some fixes in the startup script which will be available on the next version of the server.

Best regards.
