### ISSUE TITLE
docker-compose.yaml version 

### ISSUE THREAD

**Issue by Dope25** [Danixu/project-zomboid-server-docker#2]
Hi,

your docker-compose.yaml file is missing the first line:

version: "3"

Without it, you are greeted with the error:
![image](https://user-images.githubusercontent.com/68992186/150010487-1572baa3-a4ea-4886-b0c1-5752d449ea7f.png)

**Comment by Danixu** [comment]
Hello,

What version of Docker Compose and SO are you using?.

Best regards

**Comment by Danixu** [comment]
Hellos,

I have added the version line. Thanks for the report.

Best regards
