### ISSUE TITLE
failed to create user database

### ISSUE THREAD

**Issue by pawl** [Danixu/project-zomboid-server-docker#4]
I tried to use `docker-compose up` with this project, and it encountered this error and didn't finish starting the server:
```
ProjectZomboidDedicatedServer_1  | LOG  : General     , 1643514858341> 2,457,320> user database "/home/steam/Zomboid/db/servertest.db"
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1643514858341> 2,457,321> java.io.IOException: No such file or directory
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1643514858341> 2,457,321> 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1643514858341> 2,457,321> 	at java.base/java.io.File.createNewFile(Unknown Source)
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1643514858342> 2,457,321> 	at zombie.network.ServerWorldDatabase.create(ServerWorldDatabase.java:310)
ProjectZomboidDedicatedServer_1  | ERROR: General     , 1643514858342> 2,457,321> 	at zombie.network.GameServer.main(GameServer.java:608)
ProjectZomboidDedicatedServer_1  | LOG  : General     , 1643514858342> 2,457,322> failed to create user database, server shut down
ProjectZomboidDedicatedServer_1  | src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
ProjectZomboidDedicatedServer_1  | src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
```

**Comment by Danixu** [comment]
Hello,

Remove the data and workshop-mods folders and let the docker-compose to create it. If the problem persist, chmod 777 those folders. Please, report which one has workerd to proceed to remove those folders or to try to upload the permission to the repository.

Best regards.

**Comment by Danixu** [comment]
Hello,

Ignore de above mensaje. I have reproduced this error and I have added a fix to the image. You'll be able to run the server without change anything just downloading the latest image. Run the following command:

```
docker-composer pull
```

It will download the latest fixed image and just running `docker-composer up -d` as usual will work.

Best regards.

**Comment by Aschenbecher** [comment]
I had the same problem after deleting the data folder, because docker in recreating the folder with root rights. When the user is a non root user, the problem of pawl was happening...

**Comment by Danixu** [comment]
Yes... I was trying to find info about how to create the folders using the current user, but I have not found anything about it. Docker create the folders using the daemon user, which is root, and then the best approach is to remove the folder and to create it manually using the mkdir command or even doing a git checkout:

```
# sudo rm -Rf data && mkdir data

or 

# sudo rm -Rf data && git checkout data
```

Be sure to run this command in the repository folder which contains the docker-compose.yml file. I have modified the image to have the correct permissions once is mounted inside the image, and now should work fine.

Best regards.

**Comment by Aschenbecher** [comment]
You can set a UUID in Dockerfile and in docker-compose.yml. All files in datafolder will have this uuid then

**Comment by Danixu** [comment]
Yes, I have already used that option in Dockerfile.

```
USER ${USER}

# Create required folders to keep their permissions on mount
RUN mkdir -p "${HOMEDIR}/Zomboid"
```

What I am not able to find is a way to set the user of the new folders created by Docker in the host machine. It always creates those folders as root (that is why I have those folders in the git repository).

Best regards.

**Comment by Aschenbecher** [comment]
It has to be set in docker-compose file ```user:  ${PID}```

**Comment by pawl** [comment]
> Hello,
> 
> Ignore de above mensaje. I have reproduced this error and I have added a fix to the image. You'll be able to run the server without change anything just downloading the latest image. Run the following command:
> 
> ```
> docker-composer pull
> ```
> 
> It will download the latest fixed image and just running `docker-composer up -d` as usual will work.
> 
> Best regards.

I tried pulling the most recent code, uncommenting `build: .` in docker-compose.yml, deleting data & workshop-mods folders, then running `docker-compose build` and `docker-compose up`. I'm still seeing the same error:
```
user database "/home/steam/Zomboid/db/servertest.db"
failed to create user database, server shut down
java.io.IOException: No such file or directory
```

I was able to use this other project's image successfully: https://github.com/PepeCitron/projectzomboid-server

Maybe the fix is in there?

**Comment by Danixu** [comment]
Hello,

Yes, that repository have a fix that is just to run the containers as root and chown the folder, but I don't like to run the containers as root and that is my problem. Maybe I'll change it to solve this probem at once.

I have found the reason why I am not able to reproduce the problem, and is because my host username and the container username are sharing their id, so permissions are OK. There are two easy ways to fix this problem on other machines that id doesn't match.

Allow to the container user to write on that folders:
```
sudo chown 1000:1000 data workshop-mods
```

or just allow to everybody to write on that folders:
```
sudo chmod 777 data workshop-mods
```

A 3rd option is to change the local folders by volumes. changing:

```
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
```

for the following:

```
    volumes:
      # Server data
      - zomboid-data:/home/steam/Zomboid
      # Workshop mods folder
      - zomboid-workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
```

Don't uncomment the build line because it tries to build the image instead to download the latest from the repository. I'll work in the init script to try the "root" method. At least the server will run as a non root user.

Best regards.

**Comment by Danixu** [comment]
Hello,

I have changed the container to root and on startup I execute the command to fix the permissions. Now it should work without problem. I have done some tests changing the owner on my folders and they were fixed.

I recommend to do a docker-compose pull to update the image.

Best regards
