### ISSUE TITLE
[Walkthrough] Running this Docker Container on a Synology NAS

### ISSUE THREAD

**Issue by kauffy** [Danixu/project-zomboid-server-docker#7]
I was able to use this container to successfully set up a server on my Synology NAS. I thought I'd leave some tips for others.

1. Don't download anything from here, but in the Synology Docker package (if it's not there, check Package Center to install it) go to "Registry" on the left. Scroll down untill you see "danixu86/project-zomboid-dedicated-server". Select it and click Download.

2. Click on the "Image" tab on the left, and wait for the download to finish. You'll see an icon to the right of the name that looks like a typical database/hard drive symbol (a segmented cylinder). This animates while it's downloading.

3. When the download is finished, click the Launch button at the top. 

4. Name the container instance (e.g., "My-PZ-Server") on the General Settings window that appears.

5. You may also want to Enable Resource limitation, just to make sure your PZ server doesn't run away all your NAS's resources. E.g., I set my CPU priority to Medium and the Memory limit to 4096. I haven't tested the performance with other people, though.

6. Click the Advanced Settings button.

7. You may want to enable auto-restart, but I wouldn't enable it yet, in case there are problems that prevent the server from starting successfully, and it just gets stuck in a crash/reboot loop for a bit. When you know it's working, you can come back and Edit this.

8. On the Volume tab, you will want to create one association-- this is connecting a directory inside the virtual container to a real directory outside of Docker and in your filesystem. This allows your server to persist between boots, and also makes it easy to edit server files and monkey about. On my system, I have a top level folder called "docker" and inside of it, I have folders for each Container I run (e.g., Minecraft, Valheim, ProjectZomboid). If you don't have such a thing, either create one, or pick a folder in your filesystem you want to connect to the container. In my situation, I did "Add Folder", then on the left, put "docker/project_zomboid" which is the full path to where I want my PZ server files to be. Then, on the right, "/home/steam/Zomboid"-- so when the container image deals with files at the path /home/steam/Zomboid, it is actually working with files that are in my docker/project_zomboid folder.

9. Next, go to the Port Settings tab. This should be pre-populated with the defaults, HOWEVER, also by default, the "Local Port"s are all set to Auto, which is likely _not_ going to give you the ports you want. What I did was simply copy and paste the values in each line of Container Port over to the same line in Local Port. What this does is connect traffic coming into your NAS at Local Port to appear inside the container as if it arrived at Container Port. We want these to be the same thing for ease.

10. Make sure that your router is also configured either with uPnP, or that you add either Firewall rules to allow traffic in on all of these ports, or if you're using a Netgear router, use Port Forwarding to direct all traffic that arrives at any of these ports to the LAN IP address of your NAS.

11. It's also very important that you do the same thing for ports 8766 and 8767-- these are so the server can validate itself with Steam. If these ports don't direct to your container, your server will show as "Not responding" to anyone who tries to connect. Overall, I had to create three different rules for these ports.

12. If you have configured your NAS with Synology's DDNS service (so you can access your NAS from outside, using its name), then players would use your Synology name as the server name. E.g., {yournasname}.synology.me and port 16261 (the default). CAVEAT: I am making an assumption here that this works, basing it on my experience with Valheim-- even though Valheim asks for the IP of the server, this name works in its place.

13. Skip the Links tab, and head to Environment.

14. There will be default values in for Environment already, but there are a few things you will need to/want to add. See the documentation for this Container. In my case, I set SERVERPRESET to Builder, MODFOLDERS to workshop,steam,mods (though I don't fully know how this works :/ ), MEMORY to 2048m (this is the memory limit for the Java Virtual Machine-- I'm not sure of the optimal value, but my server ran okay for me, alone with this 2GB setting), and then I set the ADMINPASSWORD.

15. Click Apply.

16. Now go to "Container" on the left. You should see your Container listed under the name you gave it, with this image name listed underneath. It should say Stopped on the right.

17. Click that switch on the right to launch it.  It will take a few minutes to be fully up and running. If you select the Container, then click Details at the top, you will get a more detailed set of tools to interact with the container. Most notably, if you click on Log or Terminal, you can see the activity of the server. The server is up and ready when you see the line "Zomboid Server is VAC Secure" in the terminal.

18. At this point, you should be able to connect to the server from your PZ client (y'know, the game itself).

19. Stuff about mods and further configuration is a rabbit hole I haven't yet gone down, but I got this running today, and because there was a lack of info about this specifically for Synology's Docker, I thought I'd save you as much trouble as I can at this point.

PS: Danixu, if you think this might be useful, feel free to use it however you wish in the repo.

**Comment by kauffy** [comment]
Excellent-- I know I was looking for something like this. It's the little fiddly bits that would easily trip me up and I wouldn't know why it wasn't working-- just that it wasn't working.

If someone comes looking to run the PZ server in Docker, they're going to wind up first at this repo (likely)-- and your instructions are robust enough that with my somewhat-limited expertise, I was able to get it up and running on my Synology, so I thought I'd fill in the pieces for others looking to do the same thing-- particularly so you don't get a heap of comments and issues on here of people asking "HOW DOES WORK MY SNOLGY?!"

I did make some notes in there, though, about the mod stuff-- getting mods running on the Docker setup seems different than on a normal dedicated server.. or am I wrong? (My SP game has like 140 mods attached-- I definitely want a lot of those on the server, and I spent some time working that out yesterday). Out of scope of this, I realize, but could also be pragmatic to offer some tips, or point people somewhere appropriate for those docs. If I figure something out, I'll write it up.

Cheers.

**Comment by Danixu** [comment]
Hello @kauffy,

The way to install the mods is the same you use in a dedicated server. The only difference is where are stored.

The procedure to install the mods in a dedicated server is modifying the server ini file in ~/Zomboid/Server/<servername>.ini to include the workshop mods in the WorkshopItems option, add the mod entry in the Mods option and start the server to allow it to download the mods. For manually installed mods they are placed inside ~/Zomboid/mods and added in the ini file Mods option.

In this Docker image, ~/Zomboid goes to the external data folder if you have used the docker-compose.yml file, or wherever you have mounted the folder in the NAS system, and the procedure is the same. The only difference is that I have also added an optional mount point to the workshop-mods folder to keep the downloaded mods and avoid to have to download it in every start.

Maybe you mean the difference between the way to do it using the "Steam" dedicated server and this one. Yeah, this is because the "Steam" version can be managed using a GUI and some menus, and this server doesn't have that GUI.
NOTE: I write "Steam" between quotes because this docker server is also the Steam version 😅, but this is just the console version which is a bit more lightweight and allows you to start it somewhere.

I have documented the way to do it in my website, but is in Spanish and I had no time to complete it with the way to do it manually with mods that are not in the Workshop (when I have written that guide I didn't know how to do it yet):

https://www.electrosoftcloud.com/servidor-dedicado-project-zomboid-en-linux/

It contains just the way to add mods from the Steam Workshop.

Regards!!

**Comment by kauffy** [comment]
One additional question:
SERVERPRESET seems to have that specific list of values-- but can other setups be used here? The way you can (e.g.) create a Custom Sandbox and then save all the settings in your SP game seems like it would make sense for a server, too.
