### ISSUE TITLE
Stable release 41.71 is up

### ISSUE THREAD

**Issue by kachunkachunk** [Danixu/project-zomboid-server-docker#8]
Hello There,

Nice work on this one - I wanted to let you know that 41.71 released a few days ago, but the container is not yet set up to obtain newer versions on-the-fly via steamcmd or otherwise. I'm admittedly not too sure how to update at this moment. But before I tried mucking around with it, I did notice your scripts were waiting for a new stable release before they could be tested or possibly completed.

As a note, I'm running this via docker run commands, not compose, so I'm not sure if that's making a difference, perhaps.

**Comment by Danixu** [comment]
Hello, thanks for the report.

I am a bit out the PZ world because the lack of free time, but I will try to update the image ASAP.
Maybe I will try to add a feature to force to update the server on boot. At least an update will be faster than a full download.

Best regards

**Comment by Danixu** [comment]
Well, good news!!

I have configured a GitHub Actions to check every 6 hours if there is a new version of PZ server. If a new version is detected, then the script will push automatically the new version to dockerhub. This will keep the image up to date.

I close this issue.

Best regards.

**Comment by kachunkachunk** [comment]
Thanks, confirmed working nicely!
